# Generated by Django 4.2.5 on 2024-02-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shirt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=50)),
                ("price", models.FloatField()),
            ],
        ),
    ]
