# Generated by Django 4.2.5 on 2024-02-21 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("electronics", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Moblie",
            new_name="Mobile",
        ),
    ]
